start:
	dotnet run ServerING.csproj --urls "http://host.docker.internal:5551;http://host.docker.internal:5552;http://host.docker.internal:5553"
	
start-mirror:
	dotnet run ServerING.csproj --urls "http://host.docker.internal:5555"