TRUNCATE TABLE public."Server" CASCADE;
TRUNCATE TABLE public."Country" CASCADE;
TRUNCATE TABLE public."Platform" CASCADE;
TRUNCATE TABLE public."WebHosting" CASCADE;
TRUNCATE TABLE public."Player" CASCADE;
TRUNCATE TABLE public."User" CASCADE;
TRUNCATE TABLE public."FavoriteServer" CASCADE;
TRUNCATE TABLE public."ServerPlayer" CASCADE;
