CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Country" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "LevelOfInterest" integer NOT NULL,
    "OverallPlayers" integer NOT NULL,
    CONSTRAINT "PK_Country" PRIMARY KEY ("Id")
);

CREATE TABLE "Platform" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Popularity" integer NOT NULL,
    "Cost" integer NOT NULL,
    CONSTRAINT "PK_Platform" PRIMARY KEY ("Id")
);

CREATE TABLE "Player" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nickname" character varying(255) NOT NULL,
    "HoursPlayed" integer NOT NULL,
    "LastPlayed" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Player" PRIMARY KEY ("Id")
);

CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Login" character varying(255) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

CREATE TABLE "WebHosting" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "PricePerMonth" integer NOT NULL,
    "SubMonths" integer NOT NULL,
    CONSTRAINT "PK_WebHosting" PRIMARY KEY ("Id")
);

CREATE TABLE "Server" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Ip" character varying(30) NOT NULL,
    "GameName" character varying(30) NOT NULL,
    "Rating" integer NOT NULL,
    "Status" integer NOT NULL,
    "HostingID" integer NOT NULL,
    "PlatformID" integer NOT NULL,
    "CountryID" integer NOT NULL,
    CONSTRAINT "PK_Server" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Server_Country_CountryID" FOREIGN KEY ("CountryID") REFERENCES "Country" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Server_Platform_PlatformID" FOREIGN KEY ("PlatformID") REFERENCES "Platform" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Server_WebHosting_HostingID" FOREIGN KEY ("HostingID") REFERENCES "WebHosting" ("Id") ON DELETE CASCADE
);

CREATE TABLE "FavoriteServer" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ServerID" integer NOT NULL,
    "UserID" integer NOT NULL,
    CONSTRAINT "PK_FavoriteServer" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FavoriteServer_Server_ServerID" FOREIGN KEY ("ServerID") REFERENCES "Server" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FavoriteServer_User_UserID" FOREIGN KEY ("UserID") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ServerPlayer" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ServerID" integer NOT NULL,
    "PlayerID" integer NOT NULL,
    CONSTRAINT "PK_ServerPlayer" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServerPlayer_Player_PlayerID" FOREIGN KEY ("PlayerID") REFERENCES "Player" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ServerPlayer_Server_ServerID" FOREIGN KEY ("ServerID") REFERENCES "Server" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_FavoriteServer_ServerID" ON "FavoriteServer" ("ServerID");

CREATE INDEX "IX_FavoriteServer_UserID" ON "FavoriteServer" ("UserID");

CREATE INDEX "IX_Server_CountryID" ON "Server" ("CountryID");

CREATE INDEX "IX_Server_HostingID" ON "Server" ("HostingID");

CREATE INDEX "IX_Server_PlatformID" ON "Server" ("PlatformID");

CREATE INDEX "IX_ServerPlayer_PlayerID" ON "ServerPlayer" ("PlayerID");

CREATE INDEX "IX_ServerPlayer_ServerID" ON "ServerPlayer" ("ServerID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221117200727_initial', '6.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Server" ADD "OwnerID" integer NOT NULL DEFAULT 1;

CREATE INDEX "IX_Server_OwnerID" ON "Server" ("OwnerID");

ALTER TABLE "Server" ADD CONSTRAINT "FK_Server_User_OwnerID" FOREIGN KEY ("OwnerID") REFERENCES "User" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221119230028_serverAddedLinkToOwner', '6.0.0');

COMMIT;

